<a href="https://colab.research.google.com/github/adalves-ufabc/2022.Q2-PLN/blob/main/2022_Q2_PLN_Notebook_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Processamento de Linguagem Natural [2022.Q2]**
Prof. Alexandre Donizeti Alves

### **Chatbot usando Python e NLTK para pesquisar documentos**

### **01. Importação das bibliotecas**

In [1]:
# pip install bs4

import bs4 as bs
import urllib.request
import re
import nltk
import numpy as np
import random
import string

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
!pip install spacy --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import spacy
spacy.__version__
#pip install spacy==2.2.3

'3.4.1'

In [6]:
nltk.__version__

'3.7'

In [7]:
!python3 -m spacy download pt

⚠ As of spaCy v3.0, shortcuts like 'pt' are deprecated. Please use the
full pipeline package name 'pt_core_news_sm' instead.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 13.0 MB 7.1 MB/s 
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')


### **02. Carregamento e pré-processamento da base de dados**

**Carregamento da base de dados**

In [8]:
dados = urllib.request.urlopen('https://pt.wikipedia.org/wiki/Intelig%C3%AAncia_artificial')

In [9]:
dados = dados.read()
dados

b'<!DOCTYPE html>\n<html class="client-nojs" lang="pt" dir="ltr">\n<head>\n<meta charset="UTF-8"/>\n<title>Intelig\xc3\xaancia artificial \xe2\x80\x93 Wikip\xc3\xa9dia, a enciclop\xc3\xa9dia livre</title>\n<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\\t.","\xc2\xa0\\t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","janeiro","fevereiro","mar\xc3\xa7o","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"],"wgRequestId":"53ca4475-203f-40d8-9363-96fd60747851","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Intelig\xc3\xaancia_artificial","wgTitle":"Intelig\xc3\xaancia artificial","wgCurRevisionId":64080779,"wgRevisionId":64080779,"wgArticleId":12722,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["!CS1 ingl\xc3\xaas-fontes e

In [13]:
dados_html = bs.BeautifulSoup(dados, 'lxml')
#dados_html

In [14]:
paragrafos = dados_html.find_all('p')

In [15]:
len(paragrafos)

112

In [16]:
paragrafos[0]

<p>
		Páginas para editores conectados <a aria-label="Saiba mais sobre edição" href="/wiki/Wikip%C3%A9dia:Boas-vindas"><span>saiba mais</span></a>
</p>

In [17]:
paragrafos[0].text

'\n\t\tPáginas para editores conectados saiba mais\n'

In [18]:
conteudo = ''
for p in paragrafos:
  conteudo += p.text

In [19]:
conteudo

'\n\t\tPáginas para editores conectados saiba mais\n\nNavegação\n\nColaboração\n\nFerramentas\n\nImprimir/exportar\n\nNoutros projetos\nConteúdoNa tecnologia, a Inteligência Artificial (de sigla: IA; do inglês: Artificial Intelligence, de sigla: AI) é a inteligência demonstrada por máquinas ao executar tarefas complexas associadas a seres inteligentes[1], além de também ser um campo de estudo acadêmico,[2] onde o principal objetivo é de executar funções de modo autônomo que. \nÉ um conceito amplo e que recebe tantas definições quanto significados diferentes à palavra inteligência.[3] É possível considerar algumas características básicas desses sistemas, como a capacidade de raciocínio (aplicar regras lógicas a um conjunto de dados disponíveis para chegar a uma conclusão), aprendizagem (aprender com os erros e acertos para que no futuro possa agir de maneira mais eficaz), reconhecer padrões (tanto padrões visuais e sensoriais, como também padrões de comportamento) e inferência (capacida

**Pré-processamento da base de dados**

In [20]:
conteudo = conteudo.lower()
conteudo

'\n\t\tpáginas para editores conectados saiba mais\n\nnavegação\n\ncolaboração\n\nferramentas\n\nimprimir/exportar\n\nnoutros projetos\nconteúdona tecnologia, a inteligência artificial (de sigla: ia; do inglês: artificial intelligence, de sigla: ai) é a inteligência demonstrada por máquinas ao executar tarefas complexas associadas a seres inteligentes[1], além de também ser um campo de estudo acadêmico,[2] onde o principal objetivo é de executar funções de modo autônomo que. \né um conceito amplo e que recebe tantas definições quanto significados diferentes à palavra inteligência.[3] é possível considerar algumas características básicas desses sistemas, como a capacidade de raciocínio (aplicar regras lógicas a um conjunto de dados disponíveis para chegar a uma conclusão), aprendizagem (aprender com os erros e acertos para que no futuro possa agir de maneira mais eficaz), reconhecer padrões (tanto padrões visuais e sensoriais, como também padrões de comportamento) e inferência (capacida

In [21]:
lista_sentencas = nltk.sent_tokenize(conteudo)
#lista_sentencas

In [22]:
len(lista_sentencas)

332

In [23]:
type(lista_sentencas)

list

In [26]:
lista_sentencas[1]

'é um conceito amplo e que recebe tantas definições quanto significados diferentes à palavra inteligência.'

In [27]:
# versao 3.0.5
pln = spacy.load('pt_core_news_sm')

In [28]:
stop_words = spacy.lang.pt.stop_words.STOP_WORDS

In [29]:
print(stop_words)

{'puderam', 'bom', 'diz', 'entre', 'sétima', 'novo', 'nossos', 'fostes', 'põem', 'cedo', 'valor', 'apoia', 'fazemos', 'porquanto', 'são', 'geral', 'nenhuma', 'possivelmente', 'vais', 'ou', 'essa', 'final', 'numa', 'bastante', 'está', 'que', 'usa', 'na', 'ser', 'parece', 'sistema', 'seus', 'próximo', 'segunda', 'sete', 'sem', 'quero', 'ver', 'cima', 'das', 'vezes', 'através', 'talvez', 'quieta', 'minhas', 'estive', 'tudo', 'nível', 'tarde', 'vai', 'sétimo', 'muitos', 'dizer', 'tal', 'oitavo', 'tanta', 'cuja', 'tais', 'dez', 'área', 'teve', 'estar', 'os', 'partir', 'porque', 'sois', 'logo', 'máximo', 'tente', 'longe', 'estivemos', 'todas', 'devem', 'esteve', 'dar', 'tem', 'estava', 'pegar', 'apenas', 'aqui', 'fará', 'então', 'fazeis', 'foi', 'tivestes', 'quieto', 'tanto', 'sou', 'lugar', 'mal', 'depois', 'a', 'tipo', 'desta', 'era', 'iniciar', 'querem', 'para', 'seis', 'ainda', 'essas', 'fim', 'neste', 'lá', 'quer', 'somente', 'vêm', 'você', 'meus', 'nada', 'aquilo', 'novos', 'treze', 'p

In [30]:
type(stop_words)

set

In [31]:
len(stop_words)

416

In [32]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
def preprocessamento(texto):
  # URLs
  texto = re.sub(r"https?://[A-Za-z0-9./]+", ' ', texto)

  # espacos em branco
  texto = re.sub(r" +", ' ', texto)

  documento = pln(texto)
  lista = []
  for token in documento:
    lista.append(token.lemma_)

  lista = [palavra for palavra in lista if palavra not in stop_words and palavra not in string.punctuation]
  lista = ' '.join([str(elemento) for elemento in lista if not elemento.isdigit()])

  return lista

In [34]:
texto_teste = 'https://www.ufabc.edu.br ' + lista_sentencas[0]
texto_teste

'https://www.ufabc.edu.br \n\t\tpáginas para editores conectados saiba mais\n\nnavegação\n\ncolaboração\n\nferramentas\n\nimprimir/exportar\n\nnoutros projetos\nconteúdona tecnologia, a inteligência artificial (de sigla: ia; do inglês: artificial intelligence, de sigla: ai) é a inteligência demonstrada por máquinas ao executar tarefas complexas associadas a seres inteligentes[1], além de também ser um campo de estudo acadêmico,[2] onde o principal objetivo é de executar funções de modo autônomo que.'

In [35]:
resultado = preprocessamento(texto_teste)
resultado

' \n\t\t página editor conectado \n\n navegação \n\n colaboração \n\n ferramento \n\n imprimir exportar \n\n em outro projeto \n conteúdona tecnologia inteligência artificial sigla de o inglês artificial intelligence sigla ai inteligência demonstrar máquina a o executar tarefa complexo associar inteligentes[1 campo estudo acadêmico,[2 principal objetivo executar função modo autônomo'

In [36]:
lista_sentencas_preprocessada = []
for i in range(len(lista_sentencas)):
  lista_sentencas_preprocessada.append(preprocessamento(lista_sentencas[i]))

In [37]:
for _ in range(5):
  i = random.randint(0, len(lista_sentencas) - 1)
  print(lista_sentencas[i])
  print(lista_sentencas_preprocessada[i])
  print('-----')

[122]
inteligências artificiais podem até mesmo produzir música utilizável em um ambiente médico, com o esforço do melomics de usar música gerada por computador para o alívio do estresse e da dor.

 inteligência artificial produzir música utilizável ambiente médico esforço de o melomics música gerar computador alívio de o estresse de o dor
-----
mas, ainda não é possível, e talvez nunca será, eliminar o fator humano, entre outros pontos, da própria avaliação de progresso dessa disciplina tecnológica.
eliminar fator humano outro de o avaliação progresso de esse disciplina tecnológico
-----
caso contrário, o programa deverá ser modificado com base nas discrepâncias encontradas durante o confronto de palavras.
caso contrário programa dever modificar base em o discrepância encontrar durante confronto palavra
-----
o programa começaria com um conjunto de personagens que queriam atingir certos objetivos, com a história como uma narração das tentativas dos personagens de executar planos para 

### **03. Frases de boas-vindas**

In [38]:
textos_boas_vindas_entrada = ('olá', 'opa', 'oi')
textos_boas_vindas_respostas = ('olá', 'opa', 'oi', 'bem-vindo', 'como você está?', 'tudo bem?')

In [39]:
'olá tudo bem'.split()

['olá', 'tudo', 'bem']

In [40]:
def responder_saudacao(texto):
  for palavra in texto.split():
    if palavra.lower() in textos_boas_vindas_entrada:
      return random.choice(textos_boas_vindas_respostas)  

In [41]:
responder_saudacao('olá tudo bem?')

'olá'

### **04. Representação TF-IDF (*Term Frequency* - *Inverse Document Frequency*)**

### *Bag of words*

- *Este é o primeiro documento*
- *Este documento é o segundo documento*

**- este é o primeiro segundo documento**
- 1 1 1 1 0 1
- 1 1 1 0 1 2

- Palavras muito frequentes "dominam" o documento e podem não representar tanta informação sobre o contexto
- Maiores "pesos" para documentos longos do que para documentos pequenos

### TF-IDF (*Term Frequency* - *Inverse Document Frequency*)

- Redimensionar a frequência das palavras pela frequência com que aparecem em todos os documentos
- **Term frequency (TF)**: frequência da palavra no documento atual - TF = (número de vezes que o termo **t** aparece no documento) / (número de termos no documento)
- **Inverse document frequency (IDF)**: quão rara é a palavra nos documentos - IDF = log(N/n), **N** é o número de documentos e **n** é o número de documentos que o termo **t** apareceu
- **TF-IDF**: importância de uma palavra para um documento em uma coleção ou corpus

- Considerando um documento com 100 palavras no qual a palavra cachorro aparece 5 vezes
- TF = 5 / 100 = 0.05
- Temos 100 documentos no total (N) e a palavra cachorro aparece aparece em 20 desses documentos (n)
- IDF = log(100 / 20) = 0.699
- TF-IDF = 0.05 * 0.699 = 0.035

- **Quanto maior o valor do peso, mais raro é o termo. Quanto menor o peso, mais comum é o termo.**

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
frases_teste = lista_sentencas_preprocessada[:3]
frases_teste

['\n\t\t página editor conectado \n\n navegação \n\n colaboração \n\n ferramento \n\n imprimir exportar \n\n em outro projeto \n conteúdona tecnologia inteligência artificial sigla de o inglês artificial intelligence sigla ai inteligência demonstrar máquina a o executar tarefa complexo associar inteligentes[1 campo estudo acadêmico,[2 principal objetivo executar função modo autônomo',
 'conceito amplo receber definição significado diferente a o palavra inteligência',
 'considerar algum característica básico de esse capacidade raciocínio aplicar regra lógico conjunto dado disponível chegar conclusão aprendizagem aprender erro acerto em o futuro agir maneira eficaz reconhecer padrão padrão visual sensorial padrão comportamento inferência capacidade conseguir aplicar raciocínio em o situação de o cotidiano']

In [44]:
frases_teste.append(frases_teste[0])
frases_teste

['\n\t\t página editor conectado \n\n navegação \n\n colaboração \n\n ferramento \n\n imprimir exportar \n\n em outro projeto \n conteúdona tecnologia inteligência artificial sigla de o inglês artificial intelligence sigla ai inteligência demonstrar máquina a o executar tarefa complexo associar inteligentes[1 campo estudo acadêmico,[2 principal objetivo executar função modo autônomo',
 'conceito amplo receber definição significado diferente a o palavra inteligência',
 'considerar algum característica básico de esse capacidade raciocínio aplicar regra lógico conjunto dado disponível chegar conclusão aprendizagem aprender erro acerto em o futuro agir maneira eficaz reconhecer padrão padrão visual sensorial padrão comportamento inferência capacidade conseguir aplicar raciocínio em o situação de o cotidiano',
 '\n\t\t página editor conectado \n\n navegação \n\n colaboração \n\n ferramento \n\n imprimir exportar \n\n em outro projeto \n conteúdona tecnologia inteligência artificial sigla de

In [45]:
vetores_palavras = TfidfVectorizer()
palavras_vetorizadas = vetores_palavras.fit_transform(frases_teste)

In [46]:
type(palavras_vetorizadas)

scipy.sparse.csr.csr_matrix

In [47]:
palavras_vetorizadas

<4x74 sparse matrix of type '<class 'numpy.float64'>'
	with 112 stored elements in Compressed Sparse Row format>

In [49]:
print(vetores_palavras.get_feature_names_out())

['acadêmico' 'acerto' 'agir' 'ai' 'algum' 'amplo' 'aplicar' 'aprender'
 'aprendizagem' 'artificial' 'associar' 'autônomo' 'básico' 'campo'
 'capacidade' 'característica' 'chegar' 'colaboração' 'complexo'
 'comportamento' 'conceito' 'conclusão' 'conectado' 'conjunto' 'conseguir'
 'considerar' 'conteúdona' 'cotidiano' 'dado' 'de' 'definição'
 'demonstrar' 'diferente' 'disponível' 'editor' 'eficaz' 'em' 'erro'
 'esse' 'estudo' 'executar' 'exportar' 'ferramento' 'função' 'futuro'
 'imprimir' 'inferência' 'inglês' 'inteligentes' 'inteligência'
 'intelligence' 'lógico' 'maneira' 'modo' 'máquina' 'navegação' 'objetivo'
 'outro' 'padrão' 'palavra' 'principal' 'projeto' 'página' 'raciocínio'
 'receber' 'reconhecer' 'regra' 'sensorial' 'sigla' 'significado'
 'situação' 'tarefa' 'tecnologia' 'visual']


In [50]:
len(vetores_palavras.get_feature_names_out())

74

In [51]:
print(vetores_palavras.vocabulary_)

{'página': 62, 'editor': 34, 'conectado': 22, 'navegação': 55, 'colaboração': 17, 'ferramento': 42, 'imprimir': 45, 'exportar': 41, 'em': 36, 'outro': 57, 'projeto': 61, 'conteúdona': 26, 'tecnologia': 72, 'inteligência': 49, 'artificial': 9, 'sigla': 68, 'de': 29, 'inglês': 47, 'intelligence': 50, 'ai': 3, 'demonstrar': 31, 'máquina': 54, 'executar': 40, 'tarefa': 71, 'complexo': 18, 'associar': 10, 'inteligentes': 48, 'campo': 13, 'estudo': 39, 'acadêmico': 0, 'principal': 60, 'objetivo': 56, 'função': 43, 'modo': 53, 'autônomo': 11, 'conceito': 20, 'amplo': 5, 'receber': 64, 'definição': 30, 'significado': 69, 'diferente': 32, 'palavra': 59, 'considerar': 25, 'algum': 4, 'característica': 15, 'básico': 12, 'esse': 38, 'capacidade': 14, 'raciocínio': 63, 'aplicar': 6, 'regra': 66, 'lógico': 51, 'conjunto': 23, 'dado': 28, 'disponível': 33, 'chegar': 16, 'conclusão': 21, 'aprendizagem': 8, 'aprender': 7, 'erro': 37, 'acerto': 1, 'futuro': 44, 'agir': 2, 'maneira': 52, 'eficaz': 35, 'r

In [52]:
print(vetores_palavras.idf_)

[1.51082562 1.91629073 1.91629073 1.51082562 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.51082562 1.51082562 1.51082562
 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073 1.51082562
 1.51082562 1.91629073 1.91629073 1.91629073 1.51082562 1.91629073
 1.91629073 1.91629073 1.51082562 1.91629073 1.91629073 1.22314355
 1.91629073 1.51082562 1.91629073 1.91629073 1.51082562 1.91629073
 1.22314355 1.91629073 1.91629073 1.51082562 1.51082562 1.51082562
 1.51082562 1.51082562 1.91629073 1.51082562 1.91629073 1.51082562
 1.51082562 1.22314355 1.51082562 1.91629073 1.91629073 1.51082562
 1.51082562 1.51082562 1.51082562 1.51082562 1.91629073 1.91629073
 1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.51082562 1.91629073 1.91629073 1.51082562
 1.51082562 1.91629073]


In [53]:
palavras_vetorizadas.todense()

matrix([[0.149183  , 0.        , 0.        , 0.149183  , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.29836599,
         0.149183  , 0.149183  , 0.        , 0.149183  , 0.        ,
         0.        , 0.        , 0.149183  , 0.149183  , 0.        ,
         0.        , 0.        , 0.149183  , 0.        , 0.        ,
         0.        , 0.149183  , 0.        , 0.        , 0.12077649,
         0.        , 0.149183  , 0.        , 0.        , 0.149183  ,
         0.        , 0.12077649, 0.        , 0.        , 0.149183  ,
         0.29836599, 0.149183  , 0.149183  , 0.149183  , 0.        ,
         0.149183  , 0.        , 0.149183  , 0.149183  , 0.24155299,
         0.149183  , 0.        , 0.        , 0.149183  , 0.149183  ,
         0.149183  , 0.149183  , 0.149183  , 0.        , 0.        ,
         0.149183  , 0.149183  , 0.149183  , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.29836599, 0.        ,
         0.        , 0.149183  , 0

In [54]:
palavras_vetorizadas.todense().shape

(4, 74)

### **05: Entendimento da similaridade por cosseno**

- Link: https://en.wikipedia.org/wiki/Cosine_similarity
- Cálculos passo a passo: https://janav.wordpress.com/2013/10/27/tf-idf-and-cosine-similarity/
- Temos duas matrizes: TF e IDF
- Cosine Similarity (d1, d2) =  Dot product(d1, d2) / ||d1|| * ||d2||

In [55]:
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
palavras_vetorizadas[0].todense()

matrix([[0.149183  , 0.        , 0.        , 0.149183  , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.29836599,
         0.149183  , 0.149183  , 0.        , 0.149183  , 0.        ,
         0.        , 0.        , 0.149183  , 0.149183  , 0.        ,
         0.        , 0.        , 0.149183  , 0.        , 0.        ,
         0.        , 0.149183  , 0.        , 0.        , 0.12077649,
         0.        , 0.149183  , 0.        , 0.        , 0.149183  ,
         0.        , 0.12077649, 0.        , 0.        , 0.149183  ,
         0.29836599, 0.149183  , 0.149183  , 0.149183  , 0.        ,
         0.149183  , 0.        , 0.149183  , 0.149183  , 0.24155299,
         0.149183  , 0.        , 0.        , 0.149183  , 0.149183  ,
         0.149183  , 0.149183  , 0.149183  , 0.        , 0.        ,
         0.149183  , 0.149183  , 0.149183  , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.29836599, 0.        ,
         0.        , 0.149183  , 0

In [57]:
cosine_similarity(palavras_vetorizadas[0], palavras_vetorizadas[1])

array([[0.05664939]])

In [58]:
cosine_similarity(palavras_vetorizadas[0], palavras_vetorizadas[3])

array([[1.]])

In [59]:
similaridade = cosine_similarity(palavras_vetorizadas[0], palavras_vetorizadas)
similaridade

array([[1.        , 0.05664939, 0.04265566, 1.        ]])

In [61]:
# ordenacao indireta
similaridade.argsort()

array([[2, 1, 0, 3]])

In [78]:
i = similaridade.argsort()[0][-2]
i

0

In [79]:
i = i.flatten()
i

array([0])

### **06: Função para o chatbot responder ao usuário**

In [80]:
def responder(texto_usuario):
  resposta_chatbot = ''
  lista_sentencas_preprocessada.append(texto_usuario)

  tfidf = TfidfVectorizer()
  palavras_vetorizadas = tfidf.fit_transform(lista_sentencas_preprocessada)

  similaridade = cosine_similarity(palavras_vetorizadas[-1], palavras_vetorizadas)

  indice_sentenca = similaridade.argsort()[0][-2]
  vetor_similar = similaridade.flatten()
  vetor_similar.sort()
  vetor_encontrado = vetor_similar[-2]

  if (vetor_encontrado == 0):
    resposta_chatbot = resposta_chatbot + 'Desculpe, mas não entendi!'
    return resposta_chatbot
  else:
    resposta_chatbot = resposta_chatbot + lista_sentencas[indice_sentenca]
    return resposta_chatbot

### **07. Conversação**

In [84]:
continuar = True
print('Olá, sou um chatbot e vou responder perguntas sobre inteligência artificial: ')
while (continuar == True):
  texto_usuario = input()
  texto_usuario = texto_usuario.lower()
  if (texto_usuario != 'sair'):
    if (responder_saudacao(texto_usuario) != None):
      print('Chatbot: ' + responder_saudacao(texto_usuario))
    else:
      print('Chatbot: ')
      print(responder(preprocessamento(texto_usuario)))
      lista_sentencas_preprocessada.remove(preprocessamento(texto_usuario))
  else:
    continuar = False
    print('Chatbot: Até breve!')

Olá, sou um chatbot e vou responder perguntas sobre inteligência artificial: 
alan turing
Chatbot: 
uma contribuição prática de alan turing foi o que se chamou depois de teste de turing (tt),[24] de 1950: em lugar de responder à pergunta "podem-se ter computadores inteligentes?"
teste turing
Chatbot: 
é interessante notar que tanto a máquina de turing quanto o teste de turing talvez derivem da visão que turing tinha de que o ser humano é uma máquina.
sair
Chatbot: Até breve!


**Referências**:

Notebook disponibilizado no Curso [Chatbots com Python e Dialogflow: O Guia para Iniciantes](https://iaexpert.academy/courses/chatbots-python-dialogflow-guia-iniciantes/).

**Mais informações**: [Create your chatbot using Python NLTK](https://medium.com/@ritidass29/create-your-chatbot-using-python-nltk-88809fa621d1).